# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 32ec821d3d6138074ff054eec24fc31dd9745c3d60775a29abe42114568589370cf59c91b16013d0ae134e187acfb20a969f10590d3a19098a8635a325d03d34

test:
  secret_key_base: 903cbd7560a1435233c0c44c6109bb458ac495b2a0a8be460f84658ef48cfdf81e4d76cd3946b0cd7bf7839a60c661c7ccb03250b70a0968570befe00a527a22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
